FROM debian:buster

RUN set -x \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    curl \
    wget \
    gnupg \
    procps \
    ssh \
    rsync \
  && rm -rf /var/lib/apt/lists/*

# Install Node

RUN set -x \
  && curl -sL https://deb.nodesource.com/setup_18.x | bash - \
  && apt-get update \
  && apt-get install -y nodejs \
  && npm install -g npm@latest

RUN set -x \
  && touch ~/.bashrc \
  && echo 'alias nodejs=node' > ~/.bashrc

RUN set -x \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update \
  && apt-get install -y yarn

# Install AWS cli

RUN set -x \
  && apt-get update \
  && apt-get install -y \
    python-pip \
    python-setuptools \
    python-wheel \
    libpython-dev \
  && pip install --upgrade awscli
