FROM andrepolischuk/node

# Install Chrome

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list

RUN set -x \
  && apt-get update \
  && apt-get install -y \
    xvfb \
    libxss1 \
    google-chrome-stable

ADD scripts/xvfb-chrome /usr/bin/xvfb-chrome
RUN ln -sf /usr/bin/xvfb-chrome /usr/bin/google-chrome

ENV CHROME_BIN /usr/bin/google-chrome

# Install Firefox

RUN set -x \
  && apt-get update \
  && apt-get install -y \
    xvfb \
    bzip2 \
    libdbus-glib-1-2

RUN wget -q -O - "https://download.mozilla.org/?product=firefox-60.0-ssl&os=linux64" | tar xjv -C /opt/
RUN ln -s /opt/firefox/firefox /usr/bin/firefox-stable

ADD scripts/xvfb-firefox /usr/bin/xvfb-firefox
RUN ln -sf /usr/bin/xvfb-firefox /usr/bin/firefox

ENV FIREFOX_BIN /usr/bin/firefox
