#!/bin/bash

_kill_procs() {
  kill -TERM $ffproc
  wait $ffproc
  kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1366x768x24}

# Start Xvfb
Xvfb :100 -ac -screen 1 $XVFB_WHD +extension RANDR -nolisten tcp &
xvfb=$!

export DISPLAY=:100

firefox-esr $@ &
ffproc=$!

wait $ffproc
wait $xvfb
